# Generated by Django 5.0.4 on 2024-05-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='flen ben foulen', max_length=50)),
                ('c_email', models.CharField(default='flen@mailbox', max_length=100)),
                ('c_message', models.TextField(default='item description')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_name', models.CharField(default='bidName', max_length=100)),
                ('bid_description', models.TextField(default='item description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_image1', models.ImageField(default=None, null=True, upload_to='bid_images/')),
                ('bid_image2', models.ImageField(default=None, null=True, upload_to='bid_images/')),
                ('bid_image3', models.ImageField(default=None, null=True, upload_to='bid_images/')),
                ('bid_image4', models.ImageField(default=None, null=True, upload_to='bid_images/')),
                ('bid_image5', models.ImageField(default=None, null=True, upload_to='bid_images/')),
                ('starting_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bid_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+216', max_length=50)),
                ('fullname', models.CharField(default='flen ben foulen', max_length=100)),
                ('adress', models.CharField(default='home sweet home', max_length=200)),
                ('city', models.CharField(default='home city', max_length=100)),
                ('email', models.CharField(default='flen@mailbox', max_length=200)),
                ('zip', models.CharField(default='1234', max_length=50)),
                ('state', models.CharField(default='state affairs XD', max_length=50)),
                ('username', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
