# Generated by Django 5.0.4 on 2024-05-02 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('username', 'fullname')},
        ),
    ]
