# Generated by Django 5.0.4 on 2024-05-08 13:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userinfo_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='end_time',
        ),
        migrations.AddField(
            model_name='bid',
            name='end_time',
            field=models.DateTimeField(default=api.models.default_end_time),
        ),
    ]
