# Generated by Django 5.0.4 on 2024-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbid',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
