# Generated by Django 5.0.4 on 2024-05-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='end_time',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image1',
            field=models.ImageField(default=None, null=True, upload_to='item_image/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image2',
            field=models.ImageField(default=None, null=True, upload_to='item_image/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image3',
            field=models.ImageField(default=None, null=True, upload_to='item_image/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image4',
            field=models.ImageField(default=None, null=True, upload_to='item_image/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image5',
            field=models.ImageField(default=None, null=True, upload_to='item_image/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
