# Generated by Django 5.0.4 on 2024-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bid_unique_together_bid_bid_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image5',
        ),
    ]
