# Generated by Django 5.0.4 on 2024-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userinfo_unique_together_userinfo_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='flen ben foulen', max_length=50)),
                ('c_email', models.CharField(default='flen@mailbox', max_length=100)),
                ('c_message', models.TextField(default='item description')),
            ],
        ),
    ]
